### ISSUE TITLE
Configuration Error following Upgrade to HA 0.109.0

### ISSUE THREAD

**Issue by Jonah1970** [ProtoThis/python-synology#40] opened 2020-04-29 19:56 UTC
I have recently upgraded to HA version 0.109.0 and noticed that my existing Synology DSM integration had been removed (entities no longer existed) so I therefore added this back in via the new flow in the Front End.  I also went though and renamed all the entities to replace the prefix "Synology DSM" as I have a second NAS to add and did not want to run into problems with duplicate names.

When I now check the config prior to restarting I receive the following error:

![image](https://user-images.githubusercontent.com/53110372/80640387-3a1f2c80-8a5b-11ea-8ca6-fe0a4b736c05.png)

This would seem to indicate that the integration is not installed but everything appears to be working just fine (there are 7 devices amd 58 entities for my 4 x drive NAS which all appear to be updating correctly).

I am looking for some guidance on how to get around this problem.

Many thanks!

**Comment by Jonah1970** [comment] 2020-04-29 20:57
I have managed to sort this out ... 
I had originally checked configuration.yaml and had assumed that 'synologydsm' has been removed by the upgrade.  I then discovered that this actually resided in my sensor.yaml file so when I then removed the config from here then HA verified and restarted OK.
It is still probably worth mentioning as others may encounter the problem.

**Comment by Quentame** [comment] 2020-05-02 14:07
The issue is not related to this library, but to HA.

And this is actually not an issue but a wrong configuration, see home-assistant/core#34858

Next time, look closely at [breaking changes introduced in 0.109.0](https://www.home-assistant.io/blog/2020/04/29/release-109/#breaking-changes) and/or the [documentation](https://www.home-assistant.io/integrations/synology_dsm/) 

Closing the issue

**Closed by Quentame** 2020-05-02 14:07 UTC
